/**
 * DATA-02 — the equivalence report.
 *
 * `verify.mjs` answers "did it hold". This answers "what is the shape of the
 * change", which is the question DATA_MODEL §3 steps 3 and 4 actually ask: a
 * pass with eleven exercises quietly leaving the `upper_body` candidate set is
 * not the same as a pass. The report is regenerated on every run and committed,
 * so the diff is the review.
 *
 * It is written for a reader who has neither the code nor a database open.
 */
import * as reviewed from './reviewed.mjs'
import { loadSchemaTaxonomy } from './taxonomy.mjs'

/**
 * @param {import('./transform.mjs').Transformed} transformed
 * @param {import('./verify.mjs').Verification} verification
 * @returns {string}
 */
export function renderReport(transformed, verification) {
  const { definitions, muscles, weights, anchors, legacyPatterns, snapshotId } = transformed
  const dispositions = countBy(anchors, (row) => row.disposition)

  const lines = [
    '# Taxonomy equivalence — DATA-02',
    '',
    'GENERATED by `npm run seed`. Do not hand-edit; `npm run seed -- --check`',
    'fails if this file has drifted from the transform.',
    '',
    `Capture: \`docs/backend/snapshot/${snapshotId}/catalog/\` — the read-only live`,
    'read of the reused project, 2026-09-18.  ',
    'Reviewed tags: `docs/backend/evidence/previous-migrations/00031_tag_exercises.sql`',
    '— authored and reviewed, never deployed (live migration history ends at',
    '`00029`), so the capture has no `component_movements` column to export and',
    'this is the only place those tags exist.',
    '',
    'Nothing here was applied to a database. Live application is TASK-072, behind',
    'the off-machine-backup gate in `docs/backend/live-inventory.md`.',
    '',
    '## 1. Preservation set',
    '',
    '| Row | Captured | Seeded | Destination |',
    '|---|---:|---:|---|',
    `| Exercise definitions | ${definitions.length} | ${definitions.length} | \`exercise_definitions\` |`,
    `| Exercise-muscle mappings | ${muscles.length} | ${muscles.length} | \`exercise_muscle_groups\` |`,
    `| Exercise-anchor links | ${anchors.length} | ${weights.length} | \`exercise_pattern_weights\` |`,
    `| Legacy movement patterns | ${legacyPatterns.length} | — | derived from \`component_movements\` |`,
    `| Reviewed anatomy tags | ${definitions.length} | ${definitions.length} | two columns of \`exercise_definitions\` |`,
    '',
    `The 173-row expectation is not reachable from this input and is not`,
    'regenerated; the audited authority is 140.',
    '',
    '## 2. What became of the 150 anchor links',
    '',
    '| Disposition | Links | Why |',
    '|---|---:|---|',
    `| \`weighted\` | ${dispositions.get('weighted') ?? 0} | the anchor names a \`movement_pattern\`; the authored ranking is preserved |`,
    `| \`dropped_non_pattern\` | ${dispositions.get('dropped_non_pattern') ?? 0} | \`surprise\` — the old enum's name for core, conditioning and mobility work |`,
    `| \`dropped_region\` | ${dispositions.get('dropped_region') ?? 0} | a \`session_focus\`, not a pattern; the capture contains none |`,
    '',
    `Of the ${weights.length} preserved weights, ${weights.filter((row) => row.isPrimary).length} are primary and`,
    `${weights.filter((row) => !row.isPrimary).length} secondary — the ranking \`exercise_pattern_weights\` exists to keep.`,
    '',
    'The dropped `surprise` links are the only content leaving the taxonomy, and',
    'the seed proves the drop is lossless: every exercise whose anchors were all',
    '`surprise` is still reachable through its preserved `exercise_role` or its',
    'preserved `sections`. That check fails the build if it ever stops holding.',
    '',
    '## 3. Weights the derivation does not reach',
    '',
    `${verification.weightsOutsideDerivation.length} preserved weights rank a pattern \`exercise_patterns\` does not derive`,
    'from the exercise\'s components, so `exercise_pattern_ranked` cannot surface',
    'them. They are seeded rather than discarded — the approved disposition is',
    'Transform, and re-tagging an exercise inside a seed would be inventing',
    'taxonomy. This is DATA_MODEL §3 step 4, "any lost primary/secondary',
    'distinctions", enumerated.',
    '',
    '| Exercise | Weight | Components | Derived |',
    '|---|---|---|---|',
    ...weights
      .filter((row) => !row.derived)
      .map((row) => {
        const definition = definitions.find((entry) => entry.id === row.exerciseId)
        const components = definition?.componentMovements.join(', ') ?? '—'
        const derived = definition?.derivedPatterns.join(', ') || '—'
        return `| \`${row.exerciseId}\` | ${row.movementPattern}${row.isPrimary ? ' (primary)' : ''} | ${components} | ${derived} |`
      }),
    '',
    '## 4. Candidate sets, derived versus original',
    '',
    'DATA_MODEL §3 step 3, across all four focuses. Both columns apply the',
    'previous function\'s role exemption, so the delta is the taxonomy change and',
    'nothing else. *With contrast* is the set the previous Edge Function actually',
    'prompted with, including its `CONTRASTING_ANCHORS` widening; that heuristic',
    'is not what `focus_pattern_map` replaces, so it is context rather than the',
    'comparison basis.',
    '',
    '| Focus | Patterns | Old anchors | Old | With contrast | New | Lost | Gained |',
    '|---|---|---|---:|---:|---:|---:|---:|',
    ...verification.focusComparisons.map(
      (row) =>
        `| \`${row.focus}\` | ${row.patterns.join(', ')} | ${row.legacyAnchors.join(', ')} | ${row.legacy} | ${row.legacyWithContrast} | ${row.derived} | ${row.lost.length} | ${row.gained.length} |`,
    ),
    '',
    ...verification.focusComparisons.flatMap((row) => [
      `**\`${row.focus}\`**  `,
      `Lost: ${row.lost.length === 0 ? '—' : row.lost.map((id) => `\`${id}\``).join(', ')}  `,
      `Gained: ${row.gained.length === 0 ? '—' : row.gained.map((id) => `\`${id}\``).join(', ')}`,
      '',
    ]),
    'Every *lost* entry appears in §3 — an exercise leaves a candidate set exactly',
    'when its old anchor outlived its components. Every *gained* entry is an',
    'exercise whose tags carry a pattern the single old anchor had no room to',
    'state: the Olympic lifts and rows gain `lower_body` through `hip-hinge`, the',
    'jerks gain `upper_body` through `vertical-press`, `high-pulls` and `swing`',
    'gain `power` through `triple-extension`. That asymmetry is the change working.',
    '',
    '## 5. The 27 legacy movement patterns',
    '',
    'Not rebuilt. Patterns derive from `component_movements`, so there is no table',
    'to keep in sync. Each row still has to be shown to carry nothing the new',
    'model cannot say: its `anchor` is the primary anchor of every exercise that',
    'pointed at it (and so is now a weight), and its `category` is a',
    '`session_focus` name — except `core`, which is a section.',
    '',
    '| Pattern | Exercises | Anchor → | Category → |',
    '|---|---:|---|---|',
    ...legacyPatterns.map(
      (row) =>
        `| \`${row.id}\` | ${row.exerciseCount} | ${row.anchor} → ${describeAnchor(row.anchorDisposition)} | ${row.category} → ${row.sessionFocus === null ? '`core` section' : `\`${row.sessionFocus}\` focus`} |`,
    ),
    '',
    `Unreferenced: ${reviewed.UNREFERENCED_LEGACY_PATTERNS.map((id) => `\`${id}\``).join(', ')} — named rather than silently absent.`,
    '',
    '## 6. Reviewed workout-anatomy tags',
    '',
    `All ${definitions.length} exercises carry a reviewed \`exercise_role\` and a component`,
    'vocabulary. The frequencies below are the independent check on migration',
    '`00031`: `DATA_MODEL.md` §3 lists the same counts, written from the live',
    'catalog before this seed existed, and they agree exactly.',
    '',
    '| Component | Tagged | Pattern |',
    '|---|---:|---|',
    ...Object.entries(reviewed.COMPONENT_FREQUENCY).map(([component, count]) => {
      const pattern = loadSchemaTaxonomy().componentPatternMap.get(component)
      return `| \`${component}\` | ${count} | ${pattern ?? '— (a demand, not a pattern)'} |`
    }),
    '',
    '| Role | Exercises |',
    '|---|---:|',
    ...Object.entries(reviewed.ROLE_FREQUENCY).map(([role, count]) => `| \`${role}\` | ${count} |`),
    '',
    '## 7. Checks',
    '',
    `${verification.checks.length} checks, ${verification.failures.length} failing.`,
    '',
    ...groupNames(verification.checks).flatMap((group) => [
      `### ${GROUP_TITLES[group] ?? group}`,
      '',
      ...verification.checks
        .filter((entry) => entry.group === group)
        .map(
          (entry) =>
            `- ${entry.ok ? 'PASS' : 'FAIL'} — ${entry.name}: ${entry.detail.replaceAll('\n', ' ').replaceAll(/\s+/g, ' ')}`,
        ),
      '',
    ]),
  ]

  return `${lines.join('\n').replace(/\n{3,}/g, '\n\n').trimEnd()}\n`
}

/** @type {Record<string, string>} */
const GROUP_TITLES = {
  counts: 'Counts',
  duplicated: 'Duplicated',
  orphaned: 'Orphaned',
  dropped: 'Dropped',
  invented: 'Invented',
  anatomy: 'Workout-anatomy tags',
  equivalence: 'Candidate-set equivalence',
}

/**
 * @param {import('./verify.mjs').Check[]} checks
 * @returns {string[]}
 */
function groupNames(checks) {
  /** @type {string[]} */
  const order = []
  for (const entry of checks) if (!order.includes(entry.group)) order.push(entry.group)
  return order
}

/**
 * @param {string} disposition
 * @returns {string}
 */
function describeAnchor(disposition) {
  if (disposition === 'weighted') return '`exercise_pattern_weights`'
  if (disposition === 'dropped_region') return 'a `session_focus`, dropped'
  return '`exercise_role` + `sections`'
}

/**
 * @template T
 * @param {T[]} rows
 * @param {(row: T) => string} key
 * @returns {Map<string, number>}
 */
function countBy(rows, key) {
  /** @type {Map<string, number>} */
  const counts = new Map()
  for (const row of rows) counts.set(key(row), (counts.get(key(row)) ?? 0) + 1)
  return counts
}
