/**
 * DATA-02 — the emitted seed.
 *
 * The artifacts these functions write are the deliverable. `npm run seed` does
 * not touch a database: it reads committed files, proves equivalence, and
 * writes SQL that TASK-072 applies once the off-machine-backup gate in
 * `docs/backend/live-inventory.md` is satisfied.
 *
 * Two properties every statement below holds to.
 *
 * **Idempotent in the strict sense.** Not merely "does not error twice" —
 * *touches nothing* twice. Each `ON CONFLICT DO UPDATE` carries a `WHERE … IS
 * DISTINCT FROM …` guard, so a re-apply updates zero rows and
 * `exercise_definitions`' `updated_at` trigger never fires. A seed that bumped
 * 140 timestamps on every run would pass a naive idempotence test and quietly
 * churn the catalog.
 *
 * **Self-verifying.** Each file ends by asserting its own count and raising if
 * it is wrong. `npm run seed` proves the numbers here; these blocks prove them
 * again against the live project at apply time, where a pre-existing row this
 * seed knows nothing about would otherwise pass unnoticed.
 */

/**
 * @param {string} value
 * @returns {string}
 */
export function literal(value) {
  return `'${value.replaceAll("'", "''")}'`
}

/**
 * @param {string | null} value
 * @returns {string}
 */
export function nullableLiteral(value) {
  return value === null ? 'null' : literal(value)
}

/**
 * @param {readonly string[]} values
 * @param {string} type
 * @returns {string} `'{}'::type` for empty — `array[]` needs a cast Postgres
 *   cannot infer from nothing, and the empty literal reads better anyway.
 */
export function arrayLiteral(values, type) {
  if (values.length === 0) return `'{}'::${type}`
  return `array[${values.map(literal).join(', ')}]::${type}`
}

/**
 * @param {Record<string, string>} value
 * @returns {string}
 */
export function jsonbLiteral(value) {
  // Sorted keys: the capture's JSON key order is Postgres' business, not a
  // fact about the catalog, and an artifact that reorders between runs is not
  // byte-stable.
  const sorted = Object.fromEntries(Object.entries(value).sort(([a], [b]) => (a < b ? -1 : 1)))
  return `${literal(JSON.stringify(sorted))}::jsonb`
}

/**
 * @param {string} title
 * @param {string} snapshotId
 * @param {string[]} notes
 * @returns {string}
 */
function header(title, snapshotId, notes) {
  return [
    `-- DATA-02 — ${title}`,
    '--',
    '-- GENERATED by `npm run seed` (scripts/catalog-seed/). Do not hand-edit:',
    '-- the next run overwrites this file, and `npm run seed -- --check` fails',
    '-- the build if it has drifted.',
    '--',
    `-- Source: docs/backend/snapshot/${snapshotId}/catalog/ (read-only live capture)`,
    '--         docs/backend/evidence/previous-migrations/00031_tag_exercises.sql',
    '--         (reviewed workout-anatomy tags; never deployed, see the audit §2)',
    '--',
    ...notes.map((note) => `--${note === '' ? '' : ` ${note}`}`),
    '',
  ].join('\n')
}

/**
 * @param {string} claim    What the assertion is for, in the reader's terms.
 * @param {string} table
 * @param {number} expected
 * @param {string} [predicate]
 * @returns {string}
 */
function assertCount(claim, table, expected, predicate) {
  const where = predicate === undefined ? '' : `\n     where ${predicate}`
  const subject = predicate === undefined ? `public.${table}` : `public.${table} (${predicate})`
  return `
-- ${claim}
do $$
declare
  actual integer;
begin
  select count(*) into actual from public.${table}${where};
  if actual <> ${expected} then
    raise exception
      'DATA-02: ${subject} holds % rows, expected ${expected}', actual;
  end if;
end;
$$;
`
}

/**
 * @param {import('./transform.mjs').Transformed} transformed
 * @returns {string}
 */
export function emitDefinitions({ definitions, snapshotId }) {
  const columns = [
    'id',
    'name',
    'equipment_options',
    'default_equipment',
    'equipment_display_names',
    'coaching_cues',
    'sections',
    'can_be_primary',
    'component_movements',
    'exercise_role',
  ]

  const values = definitions
    .map(
      (row) =>
        `  (${[
          literal(row.id),
          literal(row.name),
          arrayLiteral(row.equipmentOptions, 'text[]'),
          literal(row.defaultEquipment),
          jsonbLiteral(row.equipmentDisplayNames),
          arrayLiteral(row.coachingCues, 'text[]'),
          arrayLiteral(row.sections, 'public.section_type[]'),
          row.canBePrimary ? 'true' : 'false',
          arrayLiteral(row.componentMovements, 'text[]'),
          `${literal(row.exerciseRole)}::public.exercise_role`,
        ].join(', ')})`,
    )
    .join(',\n')

  const updatable = columns.filter((column) => column !== 'id')

  // `regression` and `progression` reference this same table, and the pairs are
  // mutually recursive (`air-squat` progresses to `split-squat`, which regresses
  // to `air-squat`). No insertion order satisfies a non-deferrable self
  // foreign key, so the links are a second pass over rows that all exist.
  const linked = definitions.filter((row) => row.regression !== null || row.progression !== null)

  const links = linked
    .map((row, index) => {
      // The first row spells its types out. Every column here can be NULL, and
      // a VALUES list of nothing but NULLs would resolve to `unknown`.
      const cast = index === 0 ? '::text' : ''
      return `    (${literal(row.id)}${cast}, ${nullableLiteral(row.regression)}${cast}, ${nullableLiteral(row.progression)}${cast})`
    })
    .join(',\n')

  return (
    header('exercise definitions', snapshotId, [
      `${definitions.length} rows. The audited preservation set; the 173-row`,
      'expectation the live audit retired is not reachable from this input.',
      '',
      'component_movements and exercise_role come from the reviewed tags, every',
      'other column verbatim from the capture — including a null regression or',
      'progression, which means "no variant authored" and is preserved as null.',
    ]) +
    `
insert into public.exercise_definitions as ed (
  ${columns.join(',\n  ')}
) values
${values}
on conflict (id) do update set
  ${updatable.map((column) => `${column} = excluded.${column}`).join(',\n  ')}
where (
  ${updatable.map((column) => `ed.${column}`).join(',\n  ')}
) is distinct from (
  ${updatable.map((column) => `excluded.${column}`).join(',\n  ')}
);

-- Progression links, second pass: every target row now exists. The IS DISTINCT
-- FROM guard keeps a re-apply at zero rows touched.
update public.exercise_definitions ed
   set regression  = v.regression,
       progression = v.progression
  from (values
${links}
  ) as v (id, regression, progression)
 where ed.id = v.id
   and (ed.regression, ed.progression) is distinct from (v.regression, v.progression);
` +
    assertCount(
      `The ${definitions.length} REQ-013 names, asserted where it can still stop an apply.`,
      'exercise_definitions',
      definitions.length,
    ) +
    assertCount(
      'The second pass landed: a null here means "no variant authored", so a\n-- missing link is indistinguishable from the real thing unless counted.',
      'exercise_definitions',
      linked.length,
      'regression is not null or progression is not null',
    )
  )
}

/**
 * @param {import('./transform.mjs').Transformed} transformed
 * @returns {string}
 */
export function emitMuscles({ muscles, snapshotId }) {
  const values = muscles
    .map(
      (row) =>
        `  (${literal(row.exerciseId)}, ${literal(row.muscleGroup)}, ${literal(row.role)}::public.muscle_role)`,
    )
    .join(',\n')

  return (
    header('exercise muscle mappings', snapshotId, [
      `${muscles.length} rows, carried across unchanged. The primary key covers`,
      'every column, so there is nothing for a conflict to update.',
    ]) +
    `
insert into public.exercise_muscle_groups (exercise_id, muscle_group, role) values
${values}
on conflict (exercise_id, muscle_group, role) do nothing;
` +
    assertCount(
      `The ${muscles.length} mappings the audit preserves.`,
      'exercise_muscle_groups',
      muscles.length,
    )
  )
}

/**
 * @param {import('./transform.mjs').Transformed} transformed
 * @returns {string}
 */
export function emitWeights({ weights, anchors, snapshotId }) {
  const dropped = anchors.filter((row) => row.disposition !== 'weighted')
  const outside = weights.filter((row) => !row.derived)

  const values = weights
    .map(
      (row) =>
        `  (${literal(row.exerciseId)}, ${literal(row.movementPattern)}::public.movement_pattern, ${row.isPrimary ? 'true' : 'false'})`,
    )
    .join(',\n')

  return (
    header('exercise pattern weights', snapshotId, [
      `${weights.length} of the ${anchors.length} captured exercise-anchor links.`,
      '',
      `The other ${dropped.length} carried a value that is not a movement pattern`,
      '("surprise" — the old enum\'s name for core, conditioning and mobility',
      'work). Each one is accounted for by the exercise\'s preserved',
      'exercise_role and sections; npm run seed fails if any is not.',
      '',
      `${outside.length} of the rows below rank a pattern that exercise_patterns`,
      'does not derive, so exercise_pattern_ranked cannot surface them. They are',
      'seeded rather than dropped — the disposition is Transform, and the',
      'authored ranking is what this table exists to keep. See',
      'docs/backend/taxonomy-equivalence.md.',
    ]) +
    `
insert into public.exercise_pattern_weights as w (exercise_id, movement_pattern, is_primary) values
${values}
on conflict (exercise_id, movement_pattern) do update set
  is_primary = excluded.is_primary
where w.is_primary is distinct from excluded.is_primary;
` +
    assertCount(
      `The ${weights.length} pattern-bearing links, transformed one for one.`,
      'exercise_pattern_weights',
      weights.length,
    ) +
    assertCount(
      'The authored ranking, which is the only thing this table is for.',
      'exercise_pattern_weights',
      weights.filter((row) => row.isPrimary).length,
      'is_primary',
    )
  )
}

/**
 * The `--dev` baseline.
 *
 * REQ-013: "a dev-only flag that creates test profile/location data **without
 * preserving prior personal rows**." Everything here is constructed from the
 * constants below. Nothing reads, copies or references the eight disposable
 * auth accounts or any personal row in the reused project — the capture this
 * seed's other artifacts come from contains no user table at all, by design
 * (`docs/process/CATALOG_MIGRATION_SCOPE.md`, Exclude).
 *
 * The owner id is supplied at apply time, not baked in. An auth user is created
 * by Supabase Auth, never by a seed, so the script resolves the id from the
 * `clear.dev_owner_id` setting and refuses to guess:
 *
 * ```sh
 * psql "$SUPABASE_DB_URL" \
 *   -c "set clear.dev_owner_id = '<uuid>'" \
 *   -f supabase/seed/090_dev_baseline.sql
 * ```
 *
 * `public.profiles` and `public.locations` are DATA-01b's tables and do not
 * exist yet. The script raises a named exception rather than silently doing
 * nothing, so an early apply says which issue it is waiting for. Values are
 * written as bare literals so Postgres coerces them to whatever DATA-01b
 * declares — enum or text — without this file having to guess.
 *
 * @param {string} snapshotId
 * @returns {string}
 */
export function emitDevBaseline(snapshotId) {
  return (
    header('dev-only owner baseline (--dev)', snapshotId, [
      'NOT part of [db.seed] in supabase/config.toml. This file is applied by',
      'hand, only against a development database, and only with an owner id',
      'supplied by the operator.',
      '',
      'Creates one profile and one default location from the constants below.',
      'It copies no prior personal row: none is available to it, and none is',
      'wanted (docs/process/CATALOG_MIGRATION_SCOPE.md).',
    ]) +
    `
do $$
declare
  owner_id uuid := nullif(current_setting('clear.dev_owner_id', true), '')::uuid;
  location_id uuid;
begin
  -- 1. The tables. DATA-01b owns them; say so rather than no-op.
  if to_regclass('public.profiles') is null or to_regclass('public.locations') is null then
    raise exception
      'DATA-02 --dev: public.profiles/public.locations do not exist yet. '
      'They are DATA-01b''s (docs/specs/DATA_MODEL.md section 5); apply this '
      'file after that migration lands.';
  end if;

  -- 2. The owner. A seed does not create auth users, and it must not invent an
  --    id that would then fail profiles' foreign key.
  if owner_id is null then
    raise exception
      'DATA-02 --dev: set clear.dev_owner_id to the auth user id to seed, e.g. '
      'psql "$SUPABASE_DB_URL" -c "set clear.dev_owner_id = ''<uuid>''" -f <this file>';
  end if;

  if not exists (select 1 from auth.users where id = owner_id) then
    raise exception
      'DATA-02 --dev: no auth user %. Sign in once to create it; this file '
      'seeds a profile for an existing account and never creates one.', owner_id;
  end if;

  -- 3. The default location, by name — the dev baseline is one location, and
  --    re-running must find the same row rather than add a second.
  select id into location_id
    from public.locations
   where user_id = owner_id and name = ${literal(DEV_LOCATION.name)};

  if location_id is null then
    insert into public.locations (user_id, name, tier, equipment, is_default)
    values (
      owner_id,
      ${literal(DEV_LOCATION.name)},
      ${literal(DEV_LOCATION.tier)},
      ${literal(toPgArray(DEV_LOCATION.equipment))},
      true
    )
    returning id into location_id;
  else
    update public.locations
       set tier = ${literal(DEV_LOCATION.tier)},
           equipment = ${literal(toPgArray(DEV_LOCATION.equipment))},
           is_default = true
     where id = location_id
       and (tier::text, equipment::text[], is_default)
           is distinct from (
             ${literal(DEV_LOCATION.tier)},
             ${literal(toPgArray(DEV_LOCATION.equipment))}::text[],
             true
           );
  end if;

  -- 4. The profile.
  insert into public.profiles (
    id, experience_level, goal_preset, enabled_sections,
    onboarding_completed, default_location_id
  )
  values (
    owner_id,
    ${literal(DEV_PROFILE.experienceLevel)},
    ${literal(DEV_PROFILE.goalPreset)},
    ${literal(toPgArray(DEV_PROFILE.enabledSections))},
    true,
    location_id
  )
  on conflict (id) do update set
    experience_level    = excluded.experience_level,
    goal_preset         = excluded.goal_preset,
    enabled_sections    = excluded.enabled_sections,
    onboarding_completed = excluded.onboarding_completed,
    default_location_id = excluded.default_location_id;

  -- 5. Exactly one default location, which is the shape the app reads.
  if (select count(*) from public.locations
       where user_id = owner_id and is_default) <> 1 then
    raise exception 'DATA-02 --dev: owner % has no single default location', owner_id;
  end if;

  raise notice 'DATA-02 --dev: profile and default location ready for %', owner_id;
end;
$$;
`
  )
}

/**
 * The dev location. `full` is `equipment_tier`'s richest value
 * (`docs/backend/evidence/previous-migrations/00001_create_enums.sql`), so a
 * dev database can generate against the whole catalog rather than a subset —
 * which is the point of a dev baseline.
 */
const DEV_LOCATION = Object.freeze({
  name: 'Dev Gym',
  tier: 'full',
  equipment: Object.freeze([
    'bodyweight',
    'barbell',
    'dumbbells',
    'kettlebells',
    'bands',
    'cable',
    'machine',
    'bench',
    'rack',
    'box',
    'rower',
    'bike',
    'sled',
  ]),
})

/**
 * The dev profile. `enabled_sections` is the `profiles` default from the
 * previous schema, unchanged; DATA_MODEL §5 lists what changes about `profiles`
 * and this is not among it.
 */
const DEV_PROFILE = Object.freeze({
  experienceLevel: 'confident',
  goalPreset: 'balanced',
  enabledSections: Object.freeze([
    'warmup',
    'primary_lift',
    'accessory',
    'core',
    'conditioning',
    'cooldown',
  ]),
})

/**
 * @param {readonly string[]} values
 * @returns {string} A Postgres array literal, which coerces to `text[]` or to
 *   an enum array without this file naming the type.
 */
function toPgArray(values) {
  return `{${values.map((value) => `"${value.replaceAll('"', '\\"')}"`).join(',')}}`
}
