-- DATA-02 — exercise definitions
--
-- GENERATED by `npm run seed` (scripts/catalog-seed/). Do not hand-edit:
-- the next run overwrites this file, and `npm run seed -- --check` fails
-- the build if it has drifted.
--
-- Source: docs/backend/snapshot/2026-09-18T162821Z/catalog/ (read-only live capture)
--         docs/backend/evidence/previous-migrations/00031_tag_exercises.sql
--         (reviewed workout-anatomy tags; never deployed, see the audit §2)
--
-- 140 rows. The audited preservation set; the 173-row
-- expectation the live audit retired is not reachable from this input.
--
-- component_movements and exercise_role come from the reviewed tags, every
-- other column verbatim from the capture — including a null regression or
-- progression, which means "no variant authored" and is preserved as null.

insert into public.exercise_definitions as ed (
  id,
  name,
  equipment_options,
  default_equipment,
  equipment_display_names,
  coaching_cues,
  sections,
  can_be_primary,
  component_movements,
  exercise_role
) values
  ('90-90-stretch', '90/90 Stretch', array['bodyweight']::text[], 'bodyweight', '{}'::jsonb, array['Both legs at 90 degrees', 'Rotate between sides', 'Hip mobility']::text[], array['warmup', 'mobility', 'cooldown']::public.section_type[], false, array['hip-mobility']::text[], 'mobility'::public.exercise_role),
  ('ab-wheel-rollout', 'Ab Wheel Rollout', array['bodyweight']::text[], 'bodyweight', '{}'::jsonb, array['Extend as far as possible', 'Keep core tight', 'Roll back with control']::text[], array['core']::public.section_type[], false, array['brace', 'scapular-control']::text[], 'stability'::public.exercise_role),
  ('air-squat', 'Air Squat', array['bodyweight']::text[], 'bodyweight', '{}'::jsonb, array['Full depth', 'Knees track over toes', 'Arms forward for balance']::text[], array['warmup', 'conditioning']::public.section_type[], false, array['knee-flexion', 'hip-mobility', 'ankle-mobility']::text[], 'activation'::public.exercise_role),
  ('arm-circles', 'Arm Circles', array['bodyweight']::text[], 'bodyweight', '{}'::jsonb, array['Small to large circles', 'Both directions', 'Shoulder warm-up']::text[], array['warmup', 'mobility']::public.section_type[], false, array['shoulder-mobility']::text[], 'activation'::public.exercise_role),
  ('arnold-press', 'Arnold Press', array['dumbbells']::text[], 'dumbbells', '{}'::jsonb, array['Rotate as you press', 'Start palms facing you', 'Full overhead lockout']::text[], array['accessory']::public.section_type[], false, array['vertical-press', 'shoulder-mobility']::text[], 'accessory'::public.exercise_role),
  ('assault-bike', 'Assault Bike', array['assault_bike']::text[], 'assault_bike', '{}'::jsonb, array['Full body effort', 'Push and pull arms', 'Pace yourself']::text[], array['conditioning']::public.section_type[], false, array['cardio-output']::text[], 'cardio'::public.exercise_role),
  ('assisted-pull-ups', 'Assisted Pull-ups', array['assisted_pullup_dip']::text[], 'assisted_pullup_dip', '{}'::jsonb, array['Full range of motion', 'Control the movement', 'Progress to less assistance']::text[], array['accessory']::public.section_type[], false, array['vertical-pull', 'scapular-control']::text[], 'accessory'::public.exercise_role),
  ('back-extension', 'Back Extension', array['bodyweight']::text[], 'bodyweight', '{}'::jsonb, array['Hinge at hips', 'Neutral spine', 'Squeeze glutes at top']::text[], array['accessory']::public.section_type[], false, array['posterior-chain-activation', 'hip-hinge']::text[], 'accessory'::public.exercise_role),
  ('back-squat', 'Back Squat', array['barbell']::text[], 'barbell', '{}'::jsonb, array['Chest up, core braced', 'Knees track over toes', 'Hip crease below knee']::text[], array['primary_lift', 'accessory']::public.section_type[], true, array['knee-flexion', 'hip-mobility', 'ankle-mobility', 'brace']::text[], 'compound_lift'::public.exercise_role),
  ('band-dislocates', 'Band Dislocates', array['resistance_bands']::text[], 'resistance_bands', '{}'::jsonb, array['Wide grip on band', 'Rotate overhead and behind', 'Shoulder mobility']::text[], array['warmup', 'mobility']::public.section_type[], false, array['shoulder-mobility', 'scapular-control']::text[], 'activation'::public.exercise_role),
  ('banded-pull-aparts', 'Banded Pull-Aparts', array['resistance_bands']::text[], 'resistance_bands', '{}'::jsonb, array['Band at shoulder height', 'Pull apart to chest', 'Squeeze shoulder blades']::text[], array['warmup', 'accessory']::public.section_type[], false, array['scapular-control', 'shoulder-mobility']::text[], 'activation'::public.exercise_role),
  ('barbell-row', 'Barbell Row (Bent Over)', array['barbell']::text[], 'barbell', '{}'::jsonb, array['Neutral spine, hinged forward', 'Bar to ribcage', 'Squeeze shoulder blades']::text[], array['primary_lift', 'accessory']::public.section_type[], true, array['horizontal-pull', 'scapular-control', 'brace', 'hip-hinge']::text[], 'compound_lift'::public.exercise_role),
  ('battle-ropes', 'Battle Ropes', array['battle_ropes']::text[], 'battle_ropes', '{}'::jsonb, array['Alternating waves', 'Core engaged', 'Athletic stance']::text[], array['conditioning']::public.section_type[], false, array['cardio-output', 'scapular-control', 'brace']::text[], 'conditioning'::public.exercise_role),
  ('bb-hip-thrust', 'Barbell Hip Thrust', array['barbell']::text[], 'barbell', '{}'::jsonb, array['Shoulders on bench', 'Drive through heels', 'Full hip extension at top']::text[], array['accessory']::public.section_type[], false, array['posterior-chain-activation']::text[], 'accessory'::public.exercise_role),
  ('bear-crawl', 'Bear Crawl', array['bodyweight']::text[], 'bodyweight', '{}'::jsonb, array['Opposite hand and foot', 'Knees low', 'Core engaged']::text[], array['conditioning', 'warmup']::public.section_type[], false, array['cardio-output', 'brace']::text[], 'conditioning'::public.exercise_role),
  ('bench-press', 'Bench Press', array['barbell', 'dumbbells']::text[], 'barbell', '{"barbell":"Barbell Bench Press","dumbbells":"Dumbbell Bench Press"}'::jsonb, array['Feet flat, back arched', 'Bar to mid-chest', 'Drive through heels']::text[], array['primary_lift', 'accessory']::public.section_type[], true, array['horizontal-press', 'scapular-control', 'brace']::text[], 'compound_lift'::public.exercise_role),
  ('bench-press-decline', 'Bench Press (Decline)', array['barbell']::text[], 'barbell', '{}'::jsonb, array['Secure feet', 'Bar to lower chest', 'Control the descent']::text[], array['primary_lift', 'accessory']::public.section_type[], true, array['horizontal-press', 'scapular-control']::text[], 'compound_lift'::public.exercise_role),
  ('bench-press-incline', 'Bench Press (Incline)', array['barbell']::text[], 'barbell', '{}'::jsonb, array['30-45 degree angle', 'Bar to upper chest', 'Shoulder blades pinched']::text[], array['primary_lift', 'accessory']::public.section_type[], true, array['horizontal-press', 'scapular-control', 'brace']::text[], 'compound_lift'::public.exercise_role),
  ('bicep-curls', 'Bicep Curls', array['dumbbells', 'barbell', 'cable_machine']::text[], 'dumbbells', '{}'::jsonb, array['Elbows fixed', 'Full range of motion', 'Control the negative']::text[], array['accessory']::public.section_type[], false, array['grip']::text[], 'accessory'::public.exercise_role),
  ('bicycles', 'Bicycles', array['bodyweight']::text[], 'bodyweight', '{}'::jsonb, array['Opposite elbow to knee', 'Extend leg fully', 'Controlled pace']::text[], array['core', 'warmup', 'conditioning']::public.section_type[], false, array['brace']::text[], 'accessory'::public.exercise_role),
  ('bird-dogs', 'Bird Dogs', array['bodyweight']::text[], 'bodyweight', '{}'::jsonb, array['On all fours', 'Extend opposite arm and leg', 'Keep hips level']::text[], array['core', 'warmup', 'mobility']::public.section_type[], false, array['brace', 'posterior-chain-activation', 'anti-rotation']::text[], 'activation'::public.exercise_role),
  ('box-jumps', 'Box Jumps', array['box']::text[], 'box', '{}'::jsonb, array['Swing arms for power', 'Land softly', 'Step down to reset']::text[], array['conditioning', 'warmup']::public.section_type[], false, array['cardio-output', 'triple-extension', 'landing-mechanics']::text[], 'conditioning'::public.exercise_role),
  ('box-squat', 'Box Squat', array['barbell', 'box']::text[], 'barbell', '{}'::jsonb, array['Sit back onto box', 'Pause briefly', 'Explode up']::text[], array['primary_lift', 'accessory']::public.section_type[], true, array['knee-flexion', 'hip-mobility', 'brace']::text[], 'compound_lift'::public.exercise_role),
  ('box-step-ups', 'Box Step-ups', array['box', 'dumbbells']::text[], 'box', '{}'::jsonb, array['Full foot on box', 'Drive through heel', 'Minimal push from rear leg']::text[], array['accessory', 'conditioning']::public.section_type[], false, array['knee-flexion', 'single-leg-stability']::text[], 'accessory'::public.exercise_role),
  ('bulgarian-split-squat', 'Bulgarian Split Squat', array['dumbbells', 'barbell', 'bodyweight']::text[], 'dumbbells', '{}'::jsonb, array['Rear foot elevated', 'Vertical shin on front leg', 'Control the descent']::text[], array['accessory']::public.section_type[], false, array['knee-flexion', 'single-leg-stability', 'hip-mobility']::text[], 'accessory'::public.exercise_role),
  ('burpees', 'Burpees', array['bodyweight']::text[], 'bodyweight', '{}'::jsonb, array['Chest to floor', 'Explosive jump', 'Full extension at top']::text[], array['conditioning', 'warmup']::public.section_type[], false, array['cardio-output', 'triple-extension', 'horizontal-press']::text[], 'conditioning'::public.exercise_role),
  ('cable-chest-flys', 'Cable Chest Flys', array['cable_machine']::text[], 'cable_machine', '{}'::jsonb, array['Constant tension', 'Hands meet at center', 'Control both directions']::text[], array['accessory']::public.section_type[], false, array['horizontal-press']::text[], 'accessory'::public.exercise_role),
  ('cable-pull-through', 'Cable Pull-Through', array['cable_machine']::text[], 'cable_machine', '{}'::jsonb, array['Face away from cable', 'Hinge and pull through', 'Squeeze glutes at top']::text[], array['accessory']::public.section_type[], false, array['hip-hinge', 'posterior-chain-activation']::text[], 'accessory'::public.exercise_role),
  ('cable-rows', 'Cable Rows', array['cable_machine']::text[], 'cable_machine', '{}'::jsonb, array['Chest up', 'Pull to stomach', 'Squeeze shoulder blades']::text[], array['accessory']::public.section_type[], false, array['horizontal-pull', 'scapular-control']::text[], 'accessory'::public.exercise_role),
  ('cable-woodchops', 'Cable Woodchops', array['cable_machine']::text[], 'cable_machine', '{}'::jsonb, array['High to low or low to high', 'Rotate through core', 'Arms stay extended']::text[], array['core']::public.section_type[], false, array['anti-rotation', 'brace']::text[], 'accessory'::public.exercise_role),
  ('cat-cow', 'Cat-Cow', array['bodyweight']::text[], 'bodyweight', '{}'::jsonb, array['Alternate arch and round', 'Move with breath', 'Full spinal movement']::text[], array['warmup', 'mobility']::public.section_type[], false, array['thoracic-mobility', 'hip-mobility']::text[], 'mobility'::public.exercise_role),
  ('childs-pose', 'Child''s Pose', array['bodyweight']::text[], 'bodyweight', '{}'::jsonb, array['Sit back on heels', 'Arms extended or by sides', 'Relax and breathe']::text[], array['warmup', 'mobility', 'cooldown']::public.section_type[], false, array['shoulder-mobility']::text[], 'mobility'::public.exercise_role),
  ('chin-ups', 'Chin-ups', array['bodyweight', 'pullup_bar']::text[], 'bodyweight', '{}'::jsonb, array['Supinated grip', 'Chin over bar', 'More bicep involvement']::text[], array['accessory']::public.section_type[], false, array['vertical-pull', 'scapular-control', 'grip', 'brace']::text[], 'compound_lift'::public.exercise_role),
  ('clean-pull', 'Clean Pull', array['barbell']::text[], 'barbell', '{}'::jsonb, array['Triple extension', 'Shrug at top', 'No catch']::text[], array['accessory']::public.section_type[], false, array['triple-extension', 'hip-hinge', 'grip']::text[], 'accessory'::public.exercise_role),
  ('close-grip-bench', 'Close-Grip Bench Press', array['barbell']::text[], 'barbell', '{}'::jsonb, array['Hands shoulder-width', 'Elbows tucked', 'Tricep emphasis']::text[], array['accessory']::public.section_type[], false, array['horizontal-press', 'brace']::text[], 'accessory'::public.exercise_role),
  ('cossack-squat-weighted', 'Cossack Squat (Weighted)', array['dumbbells', 'kettlebells']::text[], 'kettlebells', '{}'::jsonb, array['Side-to-side movement', 'Heel stays down', 'Full depth on working leg']::text[], array['accessory']::public.section_type[], false, array['knee-flexion', 'hip-mobility', 'ankle-mobility']::text[], 'accessory'::public.exercise_role),
  ('couch-stretch', 'Couch Stretch', array['bodyweight']::text[], 'bodyweight', '{}'::jsonb, array['Back foot on wall or couch', 'Squeeze glute', 'Hip flexor stretch']::text[], array['warmup', 'mobility', 'cooldown']::public.section_type[], false, array['hip-mobility', 'knee-flexion']::text[], 'mobility'::public.exercise_role),
  ('curl-to-press', 'Curl to Press', array['dumbbells']::text[], 'dumbbells', '{}'::jsonb, array['Curl then press overhead', 'One fluid motion', 'Control both phases']::text[], array['accessory']::public.section_type[], false, array['vertical-press', 'grip']::text[], 'accessory'::public.exercise_role),
  ('db-chest-flys', 'Dumbbell Chest Flys', array['dumbbells']::text[], 'dumbbells', '{}'::jsonb, array['Slight elbow bend', 'Wide arc motion', 'Squeeze chest at top']::text[], array['accessory']::public.section_type[], false, array['horizontal-press']::text[], 'accessory'::public.exercise_role),
  ('db-incline-press', 'Dumbbell Incline Press', array['dumbbells']::text[], 'dumbbells', '{}'::jsonb, array['30-45 degree angle', 'Weights touch at top', 'Full stretch at bottom']::text[], array['accessory']::public.section_type[], false, array['horizontal-press']::text[], 'accessory'::public.exercise_role),
  ('db-thruster', 'Dumbbell Thruster', array['dumbbells']::text[], 'dumbbells', '{}'::jsonb, array['Dumbbells at shoulders', 'Full squat depth', 'Press overhead at top']::text[], array['accessory', 'conditioning']::public.section_type[], false, array['knee-flexion', 'vertical-press', 'triple-extension', 'brace']::text[], 'compound_lift'::public.exercise_role),
  ('dead-bugs', 'Dead Bugs', array['bodyweight']::text[], 'bodyweight', '{}'::jsonb, array['Lower back flat', 'Opposite arm and leg extend', 'Control the movement']::text[], array['core', 'warmup', 'mobility']::public.section_type[], false, array['brace', 'anti-rotation']::text[], 'activation'::public.exercise_role),
  ('deadlift', 'Deadlift', array['barbell']::text[], 'barbell', '{}'::jsonb, array['Neutral spine', 'Bar close to body', 'Hip and knee extension together']::text[], array['primary_lift', 'accessory']::public.section_type[], true, array['hip-hinge', 'posterior-chain-activation', 'grip', 'brace']::text[], 'compound_lift'::public.exercise_role),
  ('decline-push-ups', 'Decline Push-ups', array['bodyweight']::text[], 'bodyweight', '{}'::jsonb, array['Feet elevated', 'Targets upper chest', 'Full range of motion']::text[], array['accessory', 'conditioning']::public.section_type[], false, array['horizontal-press', 'brace']::text[], 'accessory'::public.exercise_role),
  ('dips', 'Dips', array['bodyweight']::text[], 'bodyweight', '{}'::jsonb, array['Lean forward for chest', 'Upright for triceps', 'Full range of motion']::text[], array['accessory']::public.section_type[], false, array['horizontal-press', 'vertical-press']::text[], 'accessory'::public.exercise_role),
  ('downward-dog', 'Downward Dog', array['bodyweight']::text[], 'bodyweight', '{}'::jsonb, array['Hips high', 'Heels toward floor', 'Straight arms']::text[], array['warmup', 'mobility', 'cooldown']::public.section_type[], false, array['hip-mobility', 'posterior-chain-activation', 'ankle-mobility']::text[], 'mobility'::public.exercise_role),
  ('external-rotation', 'External Rotation', array['cable_machine', 'resistance_bands']::text[], 'cable_machine', '{}'::jsonb, array['Elbow at 90 degrees', 'Rotate outward', 'Rotator cuff health']::text[], array['accessory']::public.section_type[], false, array['shoulder-mobility']::text[], 'accessory'::public.exercise_role),
  ('face-pulls', 'Face Pulls', array['cable_machine', 'resistance_bands']::text[], 'cable_machine', '{}'::jsonb, array['Pull to face level', 'External rotation at peak', 'Squeeze rear delts']::text[], array['accessory']::public.section_type[], false, array['scapular-control', 'shoulder-mobility']::text[], 'accessory'::public.exercise_role),
  ('farmers-carry', 'Farmers Carry', array['dumbbells', 'kettlebells']::text[], 'dumbbells', '{}'::jsonb, array['Tall posture', 'Shoulders back', 'Controlled steps']::text[], array['accessory', 'conditioning']::public.section_type[], false, array['brace', 'grip']::text[], 'stability'::public.exercise_role),
  ('flutter-kicks', 'Flutter Kicks', array['bodyweight']::text[], 'bodyweight', '{}'::jsonb, array['Lower back pressed down', 'Small kicks', 'Continuous movement']::text[], array['core', 'warmup', 'conditioning']::public.section_type[], false, array['brace']::text[], 'accessory'::public.exercise_role),
  ('foam-rolling', 'Foam Rolling', array['foam_roller']::text[], 'foam_roller', '{}'::jsonb, array['Roll slowly', 'Pause on tight spots', 'Breathe through discomfort']::text[], array['warmup', 'cooldown']::public.section_type[], false, array['hip-mobility', 'posterior-chain-activation']::text[], 'mobility'::public.exercise_role),
  ('front-squat', 'Front Squat', array['barbell']::text[], 'barbell', '{}'::jsonb, array['Elbows high, upper back tight', 'Upright torso', 'Full depth']::text[], array['primary_lift', 'accessory']::public.section_type[], true, array['knee-flexion', 'hip-mobility', 'ankle-mobility', 'brace']::text[], 'compound_lift'::public.exercise_role),
  ('frontal-raises', 'Frontal Raises', array['dumbbells']::text[], 'dumbbells', '{}'::jsonb, array['Lift to shoulder height', 'Control the descent', 'Avoid swinging']::text[], array['accessory']::public.section_type[], false, array['vertical-press']::text[], 'accessory'::public.exercise_role),
  ('glute-bridge', 'Glute Bridge', array['bodyweight', 'dumbbells', 'barbell']::text[], 'bodyweight', '{"barbell":"Barbell Glute Bridge","bodyweight":"Bodyweight Glute Bridge","dumbbells":"Dumbbell Glute Bridge"}'::jsonb, array['Feet hip-width', 'Squeeze glutes at top', 'Do not hyperextend']::text[], array['accessory']::public.section_type[], false, array['posterior-chain-activation', 'hip-hinge']::text[], 'activation'::public.exercise_role),
  ('goblet-reverse-lunges', 'Goblet Reverse Lunges', array['dumbbells', 'kettlebells']::text[], 'dumbbells', '{}'::jsonb, array['Weight at chest', 'Step back with control', 'Front knee stable']::text[], array['accessory']::public.section_type[], false, array['knee-flexion', 'single-leg-stability']::text[], 'accessory'::public.exercise_role),
  ('goblet-squat', 'Goblet Squat', array['dumbbells', 'kettlebells']::text[], 'dumbbells', '{"dumbbells":"Dumbbell Goblet Squat","kettlebells":"Kettlebell Goblet Squat"}'::jsonb, array['Weight at chest', 'Elbows inside knees', 'Upright torso']::text[], array['accessory', 'warmup']::public.section_type[], false, array['knee-flexion', 'hip-mobility', 'ankle-mobility', 'brace']::text[], 'accessory'::public.exercise_role),
  ('good-morning', 'Good Morning', array['barbell']::text[], 'barbell', '{}'::jsonb, array['Bar on back', 'Hinge at hips', 'Slight knee bend']::text[], array['accessory']::public.section_type[], false, array['hip-hinge', 'posterior-chain-activation', 'brace']::text[], 'accessory'::public.exercise_role),
  ('hack-squat', 'Hack Squat', array['hack_squat']::text[], 'hack_squat', '{}'::jsonb, array['Shoulder pads secure', 'Full depth', 'Control the negative']::text[], array['accessory']::public.section_type[], false, array['knee-flexion']::text[], 'accessory'::public.exercise_role),
  ('hammer-curls', 'Hammer Curls', array['dumbbells']::text[], 'dumbbells', '{}'::jsonb, array['Neutral grip', 'Targets brachialis', 'No swinging']::text[], array['accessory']::public.section_type[], false, array['grip']::text[], 'accessory'::public.exercise_role),
  ('hang-clean', 'Hang Clean', array['barbell']::text[], 'barbell', '{}'::jsonb, array['Start at hang position', 'Explosive hip drive', 'Fast turnover']::text[], array['primary_lift', 'accessory']::public.section_type[], true, array['triple-extension', 'hip-hinge', 'posterior-chain-activation', 'grip']::text[], 'compound_lift'::public.exercise_role),
  ('hang-snatch', 'Hang Snatch', array['barbell']::text[], 'barbell', '{}'::jsonb, array['Start at hang', 'Wide grip', 'Catch overhead']::text[], array['primary_lift', 'accessory']::public.section_type[], true, array['triple-extension', 'hip-hinge', 'shoulder-mobility', 'grip']::text[], 'compound_lift'::public.exercise_role),
  ('hanging-knee-tucks', 'Hanging Knee Tucks', array['pullup_bar']::text[], 'pullup_bar', '{}'::jsonb, array['Dead hang start', 'Bring knees to chest', 'Control the descent']::text[], array['core']::public.section_type[], false, array['brace', 'grip']::text[], 'accessory'::public.exercise_role),
  ('hanging-leg-raises', 'Hanging Leg Raises', array['pullup_bar']::text[], 'pullup_bar', '{}'::jsonb, array['Dead hang', 'Straight legs to parallel', 'Control the descent']::text[], array['core']::public.section_type[], false, array['brace', 'grip']::text[], 'accessory'::public.exercise_role),
  ('high-pulls', 'High Pulls', array['kettlebells', 'dumbbells']::text[], 'kettlebells', '{}'::jsonb, array['Explosive hip drive', 'Elbows high', 'Weight close to body']::text[], array['accessory', 'conditioning']::public.section_type[], false, array['triple-extension', 'scapular-control']::text[], 'accessory'::public.exercise_role),
  ('hip-circles', 'Hip Circles', array['bodyweight']::text[], 'bodyweight', '{}'::jsonb, array['Standing or all fours', 'Full range of motion', 'Both directions']::text[], array['warmup', 'mobility']::public.section_type[], false, array['hip-mobility']::text[], 'mobility'::public.exercise_role),
  ('hip-thrust', 'Hip Thrust', array['dumbbells', 'bodyweight']::text[], 'bodyweight', '{"bodyweight":"Bodyweight Hip Thrust","dumbbells":"Dumbbell Hip Thrust"}'::jsonb, array['Shoulders on bench', 'Drive through heels', 'Full hip extension at top']::text[], array['accessory']::public.section_type[], false, array['posterior-chain-activation']::text[], 'accessory'::public.exercise_role),
  ('hollow-body-hold', 'Hollow Body Hold', array['bodyweight']::text[], 'bodyweight', '{}'::jsonb, array['Lower back pressed to floor', 'Arms and legs extended', 'No arch in back']::text[], array['core', 'warmup']::public.section_type[], false, array['brace']::text[], 'activation'::public.exercise_role),
  ('incline-db-fly', 'Incline Dumbbell Fly', array['dumbbells']::text[], 'dumbbells', '{}'::jsonb, array['Incline bench', 'Wide arc', 'Upper chest focus']::text[], array['accessory']::public.section_type[], false, array['horizontal-press']::text[], 'accessory'::public.exercise_role),
  ('internal-rotation', 'Internal Rotation', array['cable_machine', 'resistance_bands']::text[], 'cable_machine', '{}'::jsonb, array['Elbow at 90 degrees', 'Rotate inward', 'Prehab exercise']::text[], array['accessory']::public.section_type[], false, array['shoulder-mobility']::text[], 'accessory'::public.exercise_role),
  ('inverted-rows', 'Inverted Rows', array['bodyweight', 'barbell']::text[], 'bodyweight', '{}'::jsonb, array['Body straight', 'Pull chest to bar', 'Scale with body angle']::text[], array['accessory']::public.section_type[], false, array['horizontal-pull', 'scapular-control', 'brace']::text[], 'accessory'::public.exercise_role),
  ('jump-rope', 'Jump Rope', array['bodyweight']::text[], 'bodyweight', '{}'::jsonb, array['Stay on balls of feet', 'Wrists do the work', 'Relaxed shoulders']::text[], array['conditioning', 'warmup']::public.section_type[], false, array['cardio-output', 'landing-mechanics']::text[], 'cardio'::public.exercise_role),
  ('l-sit', 'L-Sit', array['bodyweight']::text[], 'bodyweight', '{}'::jsonb, array['Legs parallel to floor', 'Arms straight', 'Depress shoulders']::text[], array['core']::public.section_type[], false, array['brace']::text[], 'accessory'::public.exercise_role),
  ('landmine-press', 'Landmine Press', array['barbell']::text[], 'barbell', '{}'::jsonb, array['Staggered stance', 'Press at angle', 'Core engaged']::text[], array['primary_lift', 'accessory']::public.section_type[], true, array['vertical-press', 'shoulder-mobility', 'scapular-control', 'brace']::text[], 'compound_lift'::public.exercise_role),
  ('landmine-rotation', 'Landmine Rotation', array['barbell']::text[], 'barbell', '{}'::jsonb, array['Rotate from hips', 'Arms extended', 'Control the arc']::text[], array['accessory', 'core']::public.section_type[], false, array['anti-rotation', 'brace']::text[], 'accessory'::public.exercise_role),
  ('lat-pulldown', 'Lat Pulldown', array['cable_machine']::text[], 'cable_machine', '{}'::jsonb, array['Lean back slightly', 'Pull to upper chest', 'Squeeze lats at bottom']::text[], array['accessory']::public.section_type[], false, array['vertical-pull', 'scapular-control']::text[], 'accessory'::public.exercise_role),
  ('lateral-lunges', 'Lateral Lunges', array['dumbbells', 'bodyweight']::text[], 'dumbbells', '{}'::jsonb, array['Step wide to side', 'Sit back into hip', 'Push back to start']::text[], array['accessory']::public.section_type[], false, array['knee-flexion', 'hip-mobility', 'single-leg-stability']::text[], 'accessory'::public.exercise_role),
  ('lateral-raises', 'Lateral Raises', array['dumbbells']::text[], 'dumbbells', '{}'::jsonb, array['Slight bend in elbow', 'Lead with pinky', 'Control the negative']::text[], array['accessory']::public.section_type[], false, array['vertical-press']::text[], 'accessory'::public.exercise_role),
  ('leg-curl', 'Leg Curl', array['leg_curl_extension']::text[], 'leg_curl_extension', '{}'::jsonb, array['Full range of motion', 'Control the negative', 'Squeeze hamstrings']::text[], array['accessory']::public.section_type[], false, array['posterior-chain-activation']::text[], 'accessory'::public.exercise_role),
  ('leg-extension', 'Leg Extension', array['leg_curl_extension']::text[], 'leg_curl_extension', '{}'::jsonb, array['Controlled movement', 'Squeeze at top', 'Do not use momentum']::text[], array['accessory']::public.section_type[], false, array['knee-flexion']::text[], 'accessory'::public.exercise_role),
  ('leg-press', 'Leg Press', array['leg_press']::text[], 'leg_press', '{}'::jsonb, array['Full range of motion', 'Do not lock knees', 'Control the negative']::text[], array['primary_lift', 'accessory']::public.section_type[], true, array['knee-flexion', 'brace']::text[], 'compound_lift'::public.exercise_role),
  ('leg-raises', 'Leg Raises', array['bodyweight']::text[], 'bodyweight', '{}'::jsonb, array['Keep legs straight', 'Lower with control', 'Press lower back down']::text[], array['core']::public.section_type[], false, array['brace']::text[], 'accessory'::public.exercise_role),
  ('leg-swings', 'Leg Swings', array['bodyweight']::text[], 'bodyweight', '{}'::jsonb, array['Forward/back and side/side', 'Controlled swing', 'Hold something for balance']::text[], array['warmup', 'mobility']::public.section_type[], false, array['hip-mobility', 'posterior-chain-activation']::text[], 'mobility'::public.exercise_role),
  ('meadows-row', 'Meadows Row', array['barbell']::text[], 'barbell', '{}'::jsonb, array['Landmine setup', 'Staggered stance', 'Pull to hip']::text[], array['accessory']::public.section_type[], false, array['horizontal-pull', 'scapular-control']::text[], 'accessory'::public.exercise_role),
  ('mountain-climbers', 'Mountain Climbers', array['bodyweight']::text[], 'bodyweight', '{}'::jsonb, array['Plank position', 'Drive knees to chest', 'Keep hips level']::text[], array['core', 'warmup', 'conditioning']::public.section_type[], false, array['cardio-output', 'brace', 'hip-mobility']::text[], 'conditioning'::public.exercise_role),
  ('muscle-clean', 'Muscle Clean', array['barbell']::text[], 'barbell', '{}'::jsonb, array['No dip under', 'Pull and turn over', 'Upper body strength']::text[], array['accessory']::public.section_type[], false, array['triple-extension', 'scapular-control', 'grip']::text[], 'accessory'::public.exercise_role),
  ('nordic-curl', 'Nordic Curl', array['bodyweight']::text[], 'bodyweight', '{}'::jsonb, array['Control the descent', 'Use hands to push back up', 'Progress slowly']::text[], array['accessory']::public.section_type[], false, array['posterior-chain-activation']::text[], 'accessory'::public.exercise_role),
  ('overhead-carry', 'Overhead Carry', array['dumbbells', 'kettlebells']::text[], 'kettlebells', '{}'::jsonb, array['Weight locked overhead', 'Core tight', 'Controlled steps']::text[], array['accessory', 'conditioning']::public.section_type[], false, array['vertical-press', 'brace', 'shoulder-mobility']::text[], 'stability'::public.exercise_role),
  ('overhead-tricep-extension', 'Overhead Tricep Extension', array['dumbbells', 'cable_machine']::text[], 'dumbbells', '{}'::jsonb, array['Elbows by ears', 'Full stretch at bottom', 'Squeeze at top']::text[], array['accessory']::public.section_type[], false, array['vertical-press']::text[], 'accessory'::public.exercise_role),
  ('pallof-press', 'Pallof Press', array['cable_machine', 'resistance_bands']::text[], 'cable_machine', '{}'::jsonb, array['Resist rotation', 'Press straight out', 'Hold at extension']::text[], array['core']::public.section_type[], false, array['anti-rotation', 'brace']::text[], 'stability'::public.exercise_role),
  ('pause-squat', 'Pause Squat', array['barbell']::text[], 'barbell', '{}'::jsonb, array['2-3 second pause at bottom', 'Stay tight in hole', 'No bounce']::text[], array['primary_lift', 'accessory']::public.section_type[], true, array['knee-flexion', 'hip-mobility', 'brace']::text[], 'compound_lift'::public.exercise_role),
  ('pendlay-row', 'Pendlay Row', array['barbell']::text[], 'barbell', '{}'::jsonb, array['Bar from floor each rep', 'Explosive pull', 'Torso parallel']::text[], array['primary_lift', 'accessory']::public.section_type[], true, array['horizontal-pull', 'scapular-control', 'brace', 'hip-hinge']::text[], 'compound_lift'::public.exercise_role),
  ('pigeon-stretch', 'Pigeon Stretch', array['bodyweight']::text[], 'bodyweight', '{}'::jsonb, array['Front shin parallel if possible', 'Square hips', 'Breathe into stretch']::text[], array['warmup', 'mobility', 'cooldown']::public.section_type[], false, array['hip-mobility', 'posterior-chain-activation']::text[], 'mobility'::public.exercise_role),
  ('plank', 'Plank', array['bodyweight']::text[], 'bodyweight', '{}'::jsonb, array['Straight line from head to heels', 'Engage core', 'Do not sag hips']::text[], array['core', 'warmup']::public.section_type[], false, array['brace']::text[], 'activation'::public.exercise_role),
  ('power-clean', 'Power Clean', array['barbell']::text[], 'barbell', '{}'::jsonb, array['Triple extension', 'High pull, fast elbows', 'Catch in quarter squat']::text[], array['primary_lift', 'accessory']::public.section_type[], true, array['triple-extension', 'hip-hinge', 'posterior-chain-activation', 'grip', 'brace']::text[], 'compound_lift'::public.exercise_role),
  ('preacher-curls', 'Preacher Curls', array['dumbbells', 'barbell']::text[], 'dumbbells', '{}'::jsonb, array['Arms on pad', 'Full extension', 'Isolation movement']::text[], array['accessory']::public.section_type[], false, array['grip']::text[], 'accessory'::public.exercise_role),
  ('pull-ups', 'Pull-ups', array['bodyweight', 'pullup_bar']::text[], 'bodyweight', '{}'::jsonb, array['Dead hang start', 'Chin over bar', 'Control the descent']::text[], array['accessory']::public.section_type[], false, array['vertical-pull', 'scapular-control', 'grip', 'brace']::text[], 'compound_lift'::public.exercise_role),
  ('push-jerk', 'Push Jerk', array['barbell']::text[], 'barbell', '{}'::jsonb, array['Dip, drive, dip under', 'Catch with soft knees', 'Stand to finish']::text[], array['primary_lift', 'accessory']::public.section_type[], true, array['triple-extension', 'vertical-press', 'brace']::text[], 'compound_lift'::public.exercise_role),
  ('push-press', 'Push Press', array['barbell', 'dumbbells']::text[], 'barbell', '{"barbell":"Barbell Push Press","dumbbells":"Dumbbell Push Press"}'::jsonb, array['Dip and drive', 'Quick hip extension', 'Catch overhead with straight arms']::text[], array['primary_lift', 'accessory']::public.section_type[], true, array['vertical-press', 'scapular-control', 'brace', 'triple-extension']::text[], 'compound_lift'::public.exercise_role),
  ('push-ups', 'Push-ups', array['bodyweight']::text[], 'bodyweight', '{}'::jsonb, array['Body in straight line', 'Chest to floor', 'Full arm extension']::text[], array['accessory', 'conditioning', 'warmup']::public.section_type[], false, array['horizontal-press', 'brace']::text[], 'accessory'::public.exercise_role),
  ('rack-carry', 'Front Rack Carry', array['kettlebells']::text[], 'kettlebells', '{}'::jsonb, array['Bells in rack position', 'Elbows up', 'Upright posture']::text[], array['accessory', 'conditioning']::public.section_type[], false, array['brace', 'grip']::text[], 'stability'::public.exercise_role),
  ('rdl', 'RDL', array['barbell', 'dumbbells', 'kettlebells']::text[], 'barbell', '{"barbell":"Barbell RDL","dumbbells":"Dumbbell RDL","kettlebells":"Kettlebell RDL"}'::jsonb, array['Slight knee bend', 'Hinge at hips', 'Feel hamstring stretch']::text[], array['primary_lift', 'accessory']::public.section_type[], true, array['hip-hinge', 'posterior-chain-activation', 'grip', 'brace']::text[], 'compound_lift'::public.exercise_role),
  ('rear-delt-flys', 'Rear Delt Flys', array['dumbbells', 'cable_machine']::text[], 'dumbbells', '{}'::jsonb, array['Bent over position', 'Lead with elbows', 'Squeeze rear delts']::text[], array['accessory']::public.section_type[], false, array['scapular-control', 'shoulder-mobility']::text[], 'accessory'::public.exercise_role),
  ('renegade-push-ups', 'Renegade Push-ups', array['dumbbells']::text[], 'dumbbells', '{}'::jsonb, array['Push-up then row', 'Minimize hip rotation', 'Wide stance for stability']::text[], array['accessory', 'conditioning']::public.section_type[], false, array['horizontal-press', 'anti-rotation', 'brace']::text[], 'accessory'::public.exercise_role),
  ('reverse-hyper', 'Reverse Hyperextension', array['bodyweight']::text[], 'bodyweight', '{}'::jsonb, array['Torso fixed', 'Lift legs with glutes', 'Control the swing']::text[], array['accessory']::public.section_type[], false, array['posterior-chain-activation', 'hip-hinge']::text[], 'accessory'::public.exercise_role),
  ('reverse-lunges', 'Reverse Lunges', array['dumbbells', 'barbell', 'bodyweight']::text[], 'dumbbells', '{}'::jsonb, array['Step back with control', 'Front knee stable', 'Drive through front heel']::text[], array['accessory']::public.section_type[], false, array['knee-flexion', 'single-leg-stability']::text[], 'accessory'::public.exercise_role),
  ('rowing-machine', 'Rowing Machine', array['rowing_machine']::text[], 'rowing_machine', '{}'::jsonb, array['Legs, back, arms sequence', 'Drive through heels', 'Controlled return']::text[], array['conditioning', 'warmup']::public.section_type[], false, array['cardio-output', 'horizontal-pull']::text[], 'cardio'::public.exercise_role),
  ('runners', 'Runners (High Knees)', array['bodyweight']::text[], 'bodyweight', '{}'::jsonb, array['Drive knees high', 'Quick turnover', 'Stay on balls of feet']::text[], array['conditioning', 'warmup']::public.section_type[], false, array['cardio-output', 'hip-mobility']::text[], 'conditioning'::public.exercise_role),
  ('russian-twists', 'Russian Twists', array['bodyweight', 'dumbbells', 'kettlebells']::text[], 'bodyweight', '{"bodyweight":"Bodyweight Russian Twists","dumbbells":"Dumbbell Russian Twists","kettlebells":"Kettlebell Russian Twists"}'::jsonb, array['Lean back slightly', 'Rotate from core', 'Feet off ground for challenge']::text[], array['core']::public.section_type[], false, array['brace']::text[], 'accessory'::public.exercise_role),
  ('shrugs', 'Shrugs', array['dumbbells', 'barbell']::text[], 'dumbbells', '{}'::jsonb, array['Straight up, not rolling', 'Hold at top', 'Control the negative']::text[], array['accessory']::public.section_type[], false, array['grip']::text[], 'accessory'::public.exercise_role),
  ('side-plank', 'Side Plank', array['bodyweight']::text[], 'bodyweight', '{}'::jsonb, array['Stack feet or stagger', 'Hips up', 'Straight line']::text[], array['core']::public.section_type[], false, array['anti-lateral-flexion', 'brace']::text[], 'stability'::public.exercise_role),
  ('single-leg-glute-bridge', 'Single-Leg Glute Bridge', array['bodyweight']::text[], 'bodyweight', '{}'::jsonb, array['One leg extended', 'Drive through heel', 'Level hips']::text[], array['accessory', 'core']::public.section_type[], false, array['posterior-chain-activation', 'single-leg-stability']::text[], 'activation'::public.exercise_role),
  ('single-leg-rdl', 'Single-Leg RDL', array['dumbbells', 'kettlebells', 'bodyweight']::text[], 'dumbbells', '{"bodyweight":"Bodyweight Single-Leg RDL","dumbbells":"Dumbbell Single-Leg RDL","kettlebells":"Kettlebell Single-Leg RDL"}'::jsonb, array['Hinge at hip', 'Back leg extends for balance', 'Square hips']::text[], array['accessory']::public.section_type[], false, array['hip-hinge', 'posterior-chain-activation', 'single-leg-stability']::text[], 'accessory'::public.exercise_role),
  ('sissy-squat', 'Sissy Squat', array['bodyweight']::text[], 'bodyweight', '{}'::jsonb, array['Lean back, knees forward', 'Heels raised', 'Quad isolation']::text[], array['accessory']::public.section_type[], false, array['knee-flexion', 'hip-mobility']::text[], 'accessory'::public.exercise_role),
  ('skull-crushers', 'Skull Crushers', array['barbell', 'dumbbells']::text[], 'barbell', '{}'::jsonb, array['Lower to forehead', 'Elbows fixed', 'Extend fully']::text[], array['accessory']::public.section_type[], false, array['vertical-press']::text[], 'accessory'::public.exercise_role),
  ('sled-pull', 'Sled Pull', array['bodyweight']::text[], 'bodyweight', '{}'::jsonb, array['Hand over hand or backward drag', 'Stay low', 'Continuous tension']::text[], array['conditioning']::public.section_type[], false, array['cardio-output', 'posterior-chain-activation']::text[], 'conditioning'::public.exercise_role),
  ('sled-push', 'Sled Push', array['bodyweight']::text[], 'bodyweight', '{}'::jsonb, array['Low body angle', 'Drive through legs', 'Short powerful steps']::text[], array['conditioning']::public.section_type[], false, array['cardio-output', 'knee-flexion']::text[], 'conditioning'::public.exercise_role),
  ('snatch', 'Snatch', array['kettlebells', 'dumbbells']::text[], 'dumbbells', '{"dumbbells":"Dumbbell Snatch","kettlebells":"Kettlebell Snatch"}'::jsonb, array['Hip snap', 'Punch through at top', 'Soft catch']::text[], array['accessory', 'conditioning']::public.section_type[], false, array['triple-extension', 'hip-hinge', 'shoulder-mobility', 'grip', 'brace']::text[], 'compound_lift'::public.exercise_role),
  ('snatch-grip-deadlift', 'Snatch-Grip Deadlift', array['barbell']::text[], 'barbell', '{}'::jsonb, array['Wide grip', 'Upper back work', 'Full extension']::text[], array['accessory']::public.section_type[], false, array['hip-hinge', 'posterior-chain-activation', 'grip', 'brace']::text[], 'compound_lift'::public.exercise_role),
  ('sotts-press', 'Sotts Press', array['dumbbells', 'kettlebells', 'barbell']::text[], 'dumbbells', '{}'::jsonb, array['Press from squat bottom', 'Core tight', 'Mobility required']::text[], array['accessory']::public.section_type[], false, array['vertical-press', 'knee-flexion', 'brace']::text[], 'accessory'::public.exercise_role),
  ('split-jerk', 'Split Jerk', array['barbell']::text[], 'barbell', '{}'::jsonb, array['Split stance catch', 'Front shin vertical', 'Recover to standing']::text[], array['primary_lift', 'accessory']::public.section_type[], true, array['triple-extension', 'vertical-press', 'single-leg-stability', 'brace']::text[], 'compound_lift'::public.exercise_role),
  ('split-squat', 'Split Squat', array['dumbbells', 'barbell', 'bodyweight']::text[], 'dumbbells', '{}'::jsonb, array['Static stance', 'Vertical torso', 'Back knee toward floor']::text[], array['accessory']::public.section_type[], false, array['knee-flexion', 'single-leg-stability']::text[], 'accessory'::public.exercise_role),
  ('squat-clean', 'Squat Clean', array['barbell']::text[], 'barbell', '{}'::jsonb, array['Full squat catch', 'Fast elbows', 'Stand up from bottom']::text[], array['primary_lift', 'accessory']::public.section_type[], true, array['triple-extension', 'knee-flexion', 'hip-hinge', 'grip', 'brace']::text[], 'compound_lift'::public.exercise_role),
  ('squat-jumps', 'Squat Jumps', array['bodyweight']::text[], 'bodyweight', '{}'::jsonb, array['Full squat depth', 'Explosive jump', 'Soft landing']::text[], array['conditioning', 'warmup']::public.section_type[], false, array['cardio-output', 'triple-extension', 'landing-mechanics']::text[], 'conditioning'::public.exercise_role),
  ('straight-arm-pulldown', 'Straight-Arm Pulldown', array['cable_machine']::text[], 'cable_machine', '{}'::jsonb, array['Arms straight throughout', 'Pull to thighs', 'Lat isolation']::text[], array['accessory']::public.section_type[], false, array['vertical-pull', 'scapular-control']::text[], 'accessory'::public.exercise_role),
  ('strict-press', 'Strict Press', array['barbell', 'dumbbells']::text[], 'barbell', '{"barbell":"Barbell Strict Press","dumbbells":"Dumbbell Strict Press"}'::jsonb, array['No leg drive', 'Bar close to face', 'Full lockout overhead']::text[], array['primary_lift', 'accessory']::public.section_type[], true, array['vertical-press', 'scapular-control', 'brace', 'shoulder-mobility']::text[], 'compound_lift'::public.exercise_role),
  ('suitcase-carry', 'Suitcase Carry', array['dumbbells', 'kettlebells']::text[], 'dumbbells', '{}'::jsonb, array['One side only', 'Stay vertical', 'Anti-lateral flexion']::text[], array['accessory', 'conditioning', 'core']::public.section_type[], false, array['anti-lateral-flexion', 'brace', 'grip']::text[], 'stability'::public.exercise_role),
  ('sumo-deadlift', 'Sumo Deadlift', array['barbell']::text[], 'barbell', '{}'::jsonb, array['Wide stance', 'Toes out', 'Push knees out']::text[], array['primary_lift', 'accessory']::public.section_type[], true, array['hip-hinge', 'posterior-chain-activation', 'grip', 'brace']::text[], 'compound_lift'::public.exercise_role),
  ('sumo-squat', 'Sumo Squat', array['barbell', 'dumbbells', 'kettlebells']::text[], 'barbell', '{}'::jsonb, array['Wide stance, toes out', 'Knees track over toes', 'Upright torso']::text[], array['primary_lift', 'accessory']::public.section_type[], true, array['knee-flexion', 'hip-mobility', 'ankle-mobility', 'brace']::text[], 'compound_lift'::public.exercise_role),
  ('swing', 'Kettlebell Swing', array['kettlebells']::text[], 'kettlebells', '{}'::jsonb, array['Hip snap, not arm pull', 'Bell to shoulder height', 'Hinge, not squat']::text[], array['accessory', 'conditioning']::public.section_type[], false, array['hip-hinge', 'posterior-chain-activation', 'triple-extension']::text[], 'accessory'::public.exercise_role),
  ('thoracic-rotations', 'Thoracic Rotations', array['bodyweight']::text[], 'bodyweight', '{}'::jsonb, array['Open up chest', 'Rotate through mid-back', 'Follow hand with eyes']::text[], array['warmup', 'mobility']::public.section_type[], false, array['thoracic-mobility']::text[], 'mobility'::public.exercise_role),
  ('three-point-row', '3-Point Row', array['dumbbells']::text[], 'dumbbells', '{}'::jsonb, array['One hand on bench', 'Row to hip', 'Minimal rotation']::text[], array['accessory']::public.section_type[], false, array['horizontal-pull', 'scapular-control', 'anti-rotation']::text[], 'accessory'::public.exercise_role),
  ('thruster', 'Thruster', array['barbell']::text[], 'barbell', '{}'::jsonb, array['Front squat to press', 'Use leg drive', 'One fluid motion']::text[], array['primary_lift', 'accessory']::public.section_type[], true, array['knee-flexion', 'vertical-press', 'triple-extension', 'brace']::text[], 'compound_lift'::public.exercise_role),
  ('toes-to-bar', 'Toes to Bar', array['pullup_bar']::text[], 'pullup_bar', '{}'::jsonb, array['Kip or strict', 'Toes touch bar', 'Control the descent']::text[], array['core']::public.section_type[], false, array['brace', 'grip']::text[], 'accessory'::public.exercise_role),
  ('trap-bar-deadlift', 'Trap Bar Deadlift', array['barbell']::text[], 'barbell', '{}'::jsonb, array['Neutral grip', 'Drive through floor', 'More quad involvement']::text[], array['primary_lift', 'accessory']::public.section_type[], true, array['hip-hinge', 'posterior-chain-activation', 'grip', 'brace', 'knee-flexion']::text[], 'compound_lift'::public.exercise_role),
  ('tricep-cable-pulldowns', 'Tricep Cable Pulldowns', array['cable_machine']::text[], 'cable_machine', '{}'::jsonb, array['Elbows pinned', 'Full extension', 'Squeeze at bottom']::text[], array['accessory']::public.section_type[], false, array['vertical-press']::text[], 'accessory'::public.exercise_role),
  ('tricep-extensions', 'Tricep Extensions', array['dumbbells', 'cable_machine']::text[], 'dumbbells', '{}'::jsonb, array['Elbows fixed', 'Full extension', 'Squeeze at bottom']::text[], array['accessory']::public.section_type[], false, array['vertical-press']::text[], 'accessory'::public.exercise_role),
  ('v-ups', 'V-Ups', array['bodyweight']::text[], 'bodyweight', '{}'::jsonb, array['Arms and legs meet at top', 'Controlled descent', 'Full body crunch']::text[], array['core']::public.section_type[], false, array['brace']::text[], 'accessory'::public.exercise_role),
  ('walking-lunges', 'Walking Lunges', array['dumbbells', 'barbell', 'bodyweight']::text[], 'dumbbells', '{}'::jsonb, array['Long stride', 'Knee tracks over toe', 'Upright torso']::text[], array['accessory']::public.section_type[], false, array['knee-flexion', 'single-leg-stability']::text[], 'accessory'::public.exercise_role),
  ('walking-lunges-oh', 'Walking Lunges (Overhead)', array['dumbbells', 'barbell']::text[], 'dumbbells', '{}'::jsonb, array['Weight locked overhead', 'Core tight', 'Controlled steps']::text[], array['accessory']::public.section_type[], false, array['knee-flexion', 'single-leg-stability', 'brace']::text[], 'accessory'::public.exercise_role),
  ('worlds-greatest-stretch', 'World''s Greatest Stretch', array['bodyweight']::text[], 'bodyweight', '{}'::jsonb, array['Lunge position', 'Rotate and reach', 'Open up hips and thoracic']::text[], array['warmup', 'mobility']::public.section_type[], false, array['hip-mobility', 'thoracic-mobility', 'ankle-mobility']::text[], 'mobility'::public.exercise_role)
on conflict (id) do update set
  name = excluded.name,
  equipment_options = excluded.equipment_options,
  default_equipment = excluded.default_equipment,
  equipment_display_names = excluded.equipment_display_names,
  coaching_cues = excluded.coaching_cues,
  sections = excluded.sections,
  can_be_primary = excluded.can_be_primary,
  component_movements = excluded.component_movements,
  exercise_role = excluded.exercise_role
where (
  ed.name,
  ed.equipment_options,
  ed.default_equipment,
  ed.equipment_display_names,
  ed.coaching_cues,
  ed.sections,
  ed.can_be_primary,
  ed.component_movements,
  ed.exercise_role
) is distinct from (
  excluded.name,
  excluded.equipment_options,
  excluded.default_equipment,
  excluded.equipment_display_names,
  excluded.coaching_cues,
  excluded.sections,
  excluded.can_be_primary,
  excluded.component_movements,
  excluded.exercise_role
);

-- Progression links, second pass: every target row now exists. The IS DISTINCT
-- FROM guard keeps a re-apply at zero rows touched.
update public.exercise_definitions ed
   set regression  = v.regression,
       progression = v.progression
  from (values
    ('air-squat'::text, null::text, 'split-squat'::text),
    ('assisted-pull-ups', null, 'lat-pulldown'),
    ('back-squat', 'goblet-squat', null),
    ('chin-ups', 'pull-ups', null),
    ('deadlift', 'rdl', null),
    ('decline-push-ups', 'push-ups', null),
    ('glute-bridge', null, 'rdl'),
    ('goblet-squat', 'air-squat', 'back-squat'),
    ('hanging-leg-raises', 'leg-raises', 'toes-to-bar'),
    ('lat-pulldown', 'assisted-pull-ups', 'pull-ups'),
    ('leg-raises', null, 'hanging-leg-raises'),
    ('pull-ups', 'lat-pulldown', 'chin-ups'),
    ('push-ups', null, 'decline-push-ups'),
    ('rdl', 'glute-bridge', 'deadlift'),
    ('split-squat', 'air-squat', 'goblet-squat'),
    ('toes-to-bar', 'hanging-leg-raises', null)
  ) as v (id, regression, progression)
 where ed.id = v.id
   and (ed.regression, ed.progression) is distinct from (v.regression, v.progression);

-- The 140 REQ-013 names, asserted where it can still stop an apply.
do $$
declare
  actual integer;
begin
  select count(*) into actual from public.exercise_definitions;
  if actual <> 140 then
    raise exception
      'DATA-02: public.exercise_definitions holds % rows, expected 140', actual;
  end if;
end;
$$;

-- The second pass landed: a null here means "no variant authored", so a
-- missing link is indistinguishable from the real thing unless counted.
do $$
declare
  actual integer;
begin
  select count(*) into actual from public.exercise_definitions
     where regression is not null or progression is not null;
  if actual <> 16 then
    raise exception
      'DATA-02: public.exercise_definitions (regression is not null or progression is not null) holds % rows, expected 16', actual;
  end if;
end;
$$;
