-- DATA-02 — exercise pattern weights
--
-- GENERATED by `npm run seed` (scripts/catalog-seed/). Do not hand-edit:
-- the next run overwrites this file, and `npm run seed -- --check` fails
-- the build if it has drifted.
--
-- Source: docs/backend/snapshot/2026-09-18T162821Z/catalog/ (read-only live capture)
--         docs/backend/evidence/previous-migrations/00031_tag_exercises.sql
--         (reviewed workout-anatomy tags; never deployed, see the audit §2)
--
-- 102 of the 150 captured exercise-anchor links.
--
-- The other 48 carried a value that is not a movement pattern
-- ("surprise" — the old enum's name for core, conditioning and mobility
-- work). Each one is accounted for by the exercise's preserved
-- exercise_role and sections; npm run seed fails if any is not.
--
-- 19 of the rows below rank a pattern that exercise_patterns
-- does not derive, so exercise_pattern_ranked cannot surface them. They are
-- seeded rather than dropped — the disposition is Transform, and the
-- authored ranking is what this table exists to keep. See
-- docs/backend/taxonomy-equivalence.md.

insert into public.exercise_pattern_weights as w (exercise_id, movement_pattern, is_primary) values
  ('air-squat', 'squat'::public.movement_pattern, true),
  ('arnold-press', 'press'::public.movement_pattern, true),
  ('assisted-pull-ups', 'pull'::public.movement_pattern, true),
  ('back-extension', 'hinge'::public.movement_pattern, true),
  ('back-squat', 'squat'::public.movement_pattern, true),
  ('barbell-row', 'pull'::public.movement_pattern, true),
  ('bb-hip-thrust', 'hinge'::public.movement_pattern, true),
  ('bench-press', 'press'::public.movement_pattern, true),
  ('bench-press-decline', 'press'::public.movement_pattern, true),
  ('bench-press-incline', 'press'::public.movement_pattern, true),
  ('bicep-curls', 'pull'::public.movement_pattern, true),
  ('box-jumps', 'power'::public.movement_pattern, false),
  ('box-squat', 'squat'::public.movement_pattern, true),
  ('box-step-ups', 'squat'::public.movement_pattern, true),
  ('bulgarian-split-squat', 'squat'::public.movement_pattern, true),
  ('burpees', 'power'::public.movement_pattern, false),
  ('cable-chest-flys', 'press'::public.movement_pattern, true),
  ('cable-pull-through', 'hinge'::public.movement_pattern, true),
  ('cable-rows', 'pull'::public.movement_pattern, true),
  ('chin-ups', 'pull'::public.movement_pattern, true),
  ('clean-pull', 'power'::public.movement_pattern, true),
  ('close-grip-bench', 'press'::public.movement_pattern, true),
  ('cossack-squat-weighted', 'squat'::public.movement_pattern, true),
  ('curl-to-press', 'pull'::public.movement_pattern, true),
  ('db-chest-flys', 'press'::public.movement_pattern, true),
  ('db-incline-press', 'press'::public.movement_pattern, true),
  ('db-thruster', 'power'::public.movement_pattern, true),
  ('db-thruster', 'press'::public.movement_pattern, false),
  ('db-thruster', 'squat'::public.movement_pattern, false),
  ('deadlift', 'hinge'::public.movement_pattern, true),
  ('deadlift', 'pull'::public.movement_pattern, false),
  ('decline-push-ups', 'press'::public.movement_pattern, true),
  ('dips', 'press'::public.movement_pattern, true),
  ('external-rotation', 'pull'::public.movement_pattern, true),
  ('face-pulls', 'pull'::public.movement_pattern, true),
  ('front-squat', 'squat'::public.movement_pattern, true),
  ('frontal-raises', 'press'::public.movement_pattern, true),
  ('glute-bridge', 'hinge'::public.movement_pattern, true),
  ('goblet-reverse-lunges', 'squat'::public.movement_pattern, true),
  ('goblet-squat', 'squat'::public.movement_pattern, true),
  ('good-morning', 'hinge'::public.movement_pattern, true),
  ('hack-squat', 'squat'::public.movement_pattern, true),
  ('hammer-curls', 'pull'::public.movement_pattern, true),
  ('hang-clean', 'power'::public.movement_pattern, true),
  ('hang-snatch', 'power'::public.movement_pattern, true),
  ('high-pulls', 'pull'::public.movement_pattern, true),
  ('hip-thrust', 'hinge'::public.movement_pattern, true),
  ('incline-db-fly', 'press'::public.movement_pattern, true),
  ('internal-rotation', 'pull'::public.movement_pattern, true),
  ('inverted-rows', 'pull'::public.movement_pattern, true),
  ('landmine-press', 'press'::public.movement_pattern, true),
  ('lat-pulldown', 'pull'::public.movement_pattern, true),
  ('lateral-lunges', 'squat'::public.movement_pattern, true),
  ('lateral-raises', 'press'::public.movement_pattern, true),
  ('leg-curl', 'hinge'::public.movement_pattern, true),
  ('leg-extension', 'squat'::public.movement_pattern, true),
  ('leg-press', 'squat'::public.movement_pattern, true),
  ('meadows-row', 'pull'::public.movement_pattern, true),
  ('muscle-clean', 'power'::public.movement_pattern, true),
  ('nordic-curl', 'hinge'::public.movement_pattern, true),
  ('overhead-tricep-extension', 'press'::public.movement_pattern, true),
  ('pause-squat', 'squat'::public.movement_pattern, true),
  ('pendlay-row', 'pull'::public.movement_pattern, true),
  ('power-clean', 'power'::public.movement_pattern, true),
  ('preacher-curls', 'pull'::public.movement_pattern, true),
  ('pull-ups', 'pull'::public.movement_pattern, true),
  ('push-jerk', 'power'::public.movement_pattern, true),
  ('push-press', 'power'::public.movement_pattern, false),
  ('push-press', 'press'::public.movement_pattern, true),
  ('push-ups', 'press'::public.movement_pattern, true),
  ('rdl', 'hinge'::public.movement_pattern, true),
  ('rear-delt-flys', 'pull'::public.movement_pattern, true),
  ('renegade-push-ups', 'press'::public.movement_pattern, true),
  ('reverse-hyper', 'hinge'::public.movement_pattern, true),
  ('reverse-lunges', 'squat'::public.movement_pattern, true),
  ('shrugs', 'pull'::public.movement_pattern, true),
  ('single-leg-glute-bridge', 'hinge'::public.movement_pattern, true),
  ('single-leg-rdl', 'hinge'::public.movement_pattern, true),
  ('single-leg-rdl', 'pull'::public.movement_pattern, false),
  ('sissy-squat', 'squat'::public.movement_pattern, true),
  ('skull-crushers', 'press'::public.movement_pattern, true),
  ('snatch', 'power'::public.movement_pattern, true),
  ('snatch-grip-deadlift', 'power'::public.movement_pattern, true),
  ('sotts-press', 'power'::public.movement_pattern, true),
  ('split-jerk', 'power'::public.movement_pattern, true),
  ('split-squat', 'squat'::public.movement_pattern, true),
  ('squat-clean', 'power'::public.movement_pattern, true),
  ('squat-jumps', 'power'::public.movement_pattern, false),
  ('straight-arm-pulldown', 'pull'::public.movement_pattern, true),
  ('strict-press', 'press'::public.movement_pattern, true),
  ('sumo-deadlift', 'hinge'::public.movement_pattern, true),
  ('sumo-squat', 'squat'::public.movement_pattern, true),
  ('swing', 'hinge'::public.movement_pattern, true),
  ('three-point-row', 'pull'::public.movement_pattern, true),
  ('thruster', 'power'::public.movement_pattern, true),
  ('thruster', 'press'::public.movement_pattern, false),
  ('thruster', 'squat'::public.movement_pattern, false),
  ('trap-bar-deadlift', 'hinge'::public.movement_pattern, true),
  ('tricep-cable-pulldowns', 'press'::public.movement_pattern, true),
  ('tricep-extensions', 'press'::public.movement_pattern, true),
  ('walking-lunges', 'squat'::public.movement_pattern, true),
  ('walking-lunges-oh', 'squat'::public.movement_pattern, true)
on conflict (exercise_id, movement_pattern) do update set
  is_primary = excluded.is_primary
where w.is_primary is distinct from excluded.is_primary;

-- The 102 pattern-bearing links, transformed one for one.
do $$
declare
  actual integer;
begin
  select count(*) into actual from public.exercise_pattern_weights;
  if actual <> 102 then
    raise exception
      'DATA-02: public.exercise_pattern_weights holds % rows, expected 102', actual;
  end if;
end;
$$;

-- The authored ranking, which is the only thing this table is for.
do $$
declare
  actual integer;
begin
  select count(*) into actual from public.exercise_pattern_weights
     where is_primary;
  if actual <> 92 then
    raise exception
      'DATA-02: public.exercise_pattern_weights (is_primary) holds % rows, expected 92', actual;
  end if;
end;
$$;
