-- Inherited history marker: 00005 create_workout_sections.
-- Already applied to the reused live project; intentionally a no-op here.
-- Why this file exists, and when it goes: supabase/migrations/README.md
