-- Inherited history marker: 00008 create_rls_policies.
-- Already applied to the reused live project; intentionally a no-op here.
-- Why this file exists, and when it goes: supabase/migrations/README.md
