-- Inherited history marker: 00009 seed_exercise_library.
-- Already applied to the reused live project; intentionally a no-op here.
-- Why this file exists, and when it goes: supabase/migrations/README.md
