-- Inherited history marker: 00011 consolidate_exercises.
-- Already applied to the reused live project; intentionally a no-op here.
-- Why this file exists, and when it goes: supabase/migrations/README.md
