-- Inherited history marker: 00016 exercise_anchors_junction.
-- Already applied to the reused live project; intentionally a no-op here.
-- Why this file exists, and when it goes: supabase/migrations/README.md
