-- Inherited history marker: 00024 create_saved_workouts.
-- Already applied to the reused live project; intentionally a no-op here.
-- Why this file exists, and when it goes: supabase/migrations/README.md
