-- Inherited history marker: 00023 save_workout_return_uuids.
-- Already applied to the reused live project; intentionally a no-op here.
-- Why this file exists, and when it goes: supabase/migrations/README.md
