-- Inherited history marker: 00025 add_exercise_structure.
-- Already applied to the reused live project; intentionally a no-op here.
-- Why this file exists, and when it goes: supabase/migrations/README.md
